name: Koolo Build CI
on:
  push:
  pull_request:
  release:

jobs:
  build:
    name: "Build Koolo binary"
    runs-on: windows-2022
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: "Building Koolo artifacts"
        env:
          GOPATH: C:\go
        run: .\build.bat "${{  github.ref_name }}"
      - name: "Packing the release"
        run: 7z a -tzip koolo_${{ github.ref_name }}.zip .\build\*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: koolo_${{ github.ref_name }}.zip
